# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convention', models.CharField(max_length=100)),
                ('refactor', models.CharField(max_length=100)),
                ('warning', models.CharField(max_length=100)),
                ('error', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('docstring', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('empty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponame', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('clase', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=100)),
                ('Repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.Repositorio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='repositorio',
            name='Autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.Usuario'),
        ),
        migrations.AddField(
            model_name='metrica',
            name='Repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.Repositorio'),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='Repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.Repositorio'),
        ),
    ]
