# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Repo', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('docstring', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('empty', models.CharField(max_length=100)),
                ('convention', models.CharField(max_length=100)),
                ('refactor', models.CharField(max_length=100)),
                ('warning', models.CharField(max_length=100)),
                ('error', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('clase', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mensajes',
            name='Repo',
        ),
        migrations.RemoveField(
            model_name='metrica',
            name='Repo',
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='Autor',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Repo',
        ),
        migrations.DeleteModel(
            name='Mensajes',
        ),
        migrations.DeleteModel(
            name='Metrica',
        ),
        migrations.DeleteModel(
            name='Repositorio',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
