# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 16:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_analisis_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='statements',
            field=models.CharField(default=datetime.datetime(2016, 2, 23, 16, 32, 52, 566301, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
