# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_analisis_statements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameppal', models.CharField(max_length=100)),
                ('notappal', models.CharField(max_length=100)),
                ('archppal', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
                ('nota1', models.CharField(max_length=100)),
                ('arch1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('nota2', models.CharField(max_length=100)),
                ('arch2', models.CharField(max_length=100)),
                ('name3', models.CharField(max_length=100)),
                ('nota3', models.CharField(max_length=100)),
                ('arch3', models.CharField(max_length=100)),
                ('name4', models.CharField(max_length=100)),
                ('nota4', models.CharField(max_length=100)),
                ('arch4', models.CharField(max_length=100)),
                ('name5', models.CharField(max_length=100)),
                ('nota5', models.CharField(max_length=100)),
                ('arch5', models.CharField(max_length=100)),
                ('name6', models.CharField(max_length=100)),
                ('nota6', models.CharField(max_length=100)),
                ('arch6', models.CharField(max_length=100)),
                ('name7', models.CharField(max_length=100)),
                ('nota7', models.CharField(max_length=100)),
                ('arch7', models.CharField(max_length=100)),
                ('name8', models.CharField(max_length=100)),
                ('nota8', models.CharField(max_length=100)),
                ('arch8', models.CharField(max_length=100)),
                ('name9', models.CharField(max_length=100)),
                ('nota9', models.CharField(max_length=100)),
                ('arch9', models.CharField(max_length=100)),
                ('war', models.CharField(max_length=100)),
                ('err', models.CharField(max_length=100)),
                ('con', models.CharField(max_length=100)),
                ('repo', models.CharField(max_length=100)),
            ],
        ),
    ]
