# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0006_historial_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameppal', models.CharField(max_length=100)),
                ('notappal', models.CharField(max_length=100)),
            ],
        ),
    ]
