# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0008_auto_20160331_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='error1',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 9, 47, 13, 557713, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='error2',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 9, 47, 38, 450227, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='error3',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 9, 48, 2, 344514, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='error4',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 9, 48, 6, 873463, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='error5',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 9, 48, 11, 272759, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='error6',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 9, 48, 14, 606834, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='error7',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 9, 48, 17, 415800, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='error8',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 9, 48, 20, 641180, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='error9',
            field=models.CharField(default=datetime.datetime(2016, 4, 14, 9, 48, 24, 336897, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
