# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0009_auto_20160414_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='error1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historial',
            name='error2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historial',
            name='error3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historial',
            name='error4',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historial',
            name='error5',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historial',
            name='error6',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historial',
            name='error7',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historial',
            name='error8',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historial',
            name='error9',
            field=models.CharField(max_length=1000),
        ),
    ]
